apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gcp-csi-driver
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/msw10100/ensemble-tech-k8s.git
    targetRevision: HEAD
    path: argocd/05-gcp-csi-driver
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true