apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: postgres
  labels:
    app: postgresql
spec:
  selector:
    app: postgresql
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  type: ClusterIP