apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: letsencrypt-issuer
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/msw10100/ensemble-tech-k8s.git
    targetRevision: main
    path: argocd/03-letsencrypt-issuer
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true